Trainset 형태를 바꾸려던 중 에러입니다
hzlcodus/tevatron pull request #1
Opened 2023-12-02 16:29 UTC by hzlcodus

## 현재까지 한 작업:
1. build_train_hn.py의 load_ranking에서 query, pos_passages, neg_passages에 더해 neg_scores까지 리턴하도록 바꾸었습니다. 제가 디버깅해보니 train.rank.tsv에 positive passage(gold)에 대한 score는 없는 건지, pos_score는 안 나왔습니다.
2. 이후 build_train_hn.py를 보면 processor로 SimpleTrainPreProcessor를 사용하므로, preprocessor_tsv.py의 L75의 process_one 함수에서 neg_score을 같이 리턴해주었습니다.
3. 이렇게 해서 create_hn.sh를 돌려서 /data/cme/marco/bert/train-hn-withscore 디렉토리에 HN 파일들을 저장했습니다. (여기까지 성공 완료)
4. train.py의 L95를 보면 TrainDataset을 사용하므로, data.py의 L46 getitem 함수에서 neg_score를 함께 처리해 리턴하도록 했습니다.
그리고 이 함수가 원래 pos_passage와 neg_passage를 통합해 하나의 passages 형태로 리턴하고 있는데, 추가로 pos_passage들도 리턴하도록 했습니다. 1번에서 pos_score가 얻지 못했기 때문에, 추후 encoder의 forward function에서 쿼리와 positive passage는 encoding해서 train time에 유사도를 계산하는 방식을 그대로 가져가야 할 것 같습니다.. encoder 내부 함수들의 인풋의 편의를 위해 pos_passage를 데이터로 같이 넣어주었습니다.
5. encoder.py에서 forward function(L96)에서 인자를 바꿔 positive_passage와 neg_score를 함께 받았습니다. L145: teacher_scores를 계산해야 하는데, 기존 코드에서는 쿼리와 모든 passage를 original LM으로 encoding 후 similarity를 구하는 과정이 있었지만, 지금은 쿼리와 positive_passage에 대해서만 따로 이 과정을 진행하고, 나머지는 neg_score로 사용하려고 합니다. 이 부분은 디버깅하기 전에 이미 에러가 나 버려서 dimension/type 확인을 더 해봐야 할 것 같습니다.
6. 테스트용으로 train_cme_hn.sh를 돌려본 결과, HFTrainDataset의 load_dataset 함수에서 문제가 발생하는데 고치지를 못하고 있습니다 ㅠㅠ sh 파일과 에러 전문은 아래에 있습니다. train.py의 L88을 보면, L95에서 TrainDataSet을 쓰기 전에, HFTrainDataset 상태로 한 번 process를 해주는데.. 문제가 발생한 건 dataset.py의 HFTrainDataset의 L24인데, 이 load_dataset 함수는 파이썬 내부 함수라서 제가 손을 댈 수가 없습니다. 어딘가 argument 설정하는 데가 있을 거라고 생각했는데, data_args.dataset_name, dataset_language는 의미없는 변수들이었습니다. (data_args는 arguments.py의 L45부터 모두 확인할 수 있습니다)

## script (train_cme_hn.sh)
저는 CUDA 메모리가 부족해서 batch size 2로 돌리고 있는데, 8이 돌아간다면 8로 해주시면 좋을 것 같습니다
```

#!/bin/bash
#SBATCH --job-name=train_cme_hn       # Submit a job named
#SBATCH --nodes=1                             # Using 1 node
#SBATCH --gres=gpu:1                          # Using 1 gpu
#SBATCH --time=0-72:00:00                     # 1 hour timelimit
#SBATCH --mem=100000MB                         # Using 10GB CPU Memory
#SBATCH --cpus-per-task=8                     # Using 4 maximum processor

export RANK=0
export WORLD_SIZE=1
export MASTER_ADDR=localhost
export MASTER_PORT=2345

CUDA_VISIBLE_DEVICES=2 python -m tevatron.driver.train --output_dir ./cme_model_KL_initbert --model_name_or_path Luyu/co-condenser-marco-retriever --save_steps 20000 --train_dir /data/cme/marco/bert/train-hn-withscore --fp16 --per_device_train_batch_size 8 --learning_rate 5e-6 --num_train_epochs 2 --dataloader_num_workers 2
```

## 에러
에러 전문은 아래와 같습니다.

```
You can remove this warning by passing 'token=True' instead.
  warnings.warn(
Downloading data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 7781.64it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 295.37it/s]
Generating train split: 59572 examples [00:04, 12072.66 examples/s]
Traceback (most recent call last):
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/builder.py", line 1940, in _prepare_split_single
    writer.write_table(table)
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/arrow_writer.py", line 572, in write_table
    pa_table = table_cast(pa_table, self._schema)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/table.py", line 2328, in table_cast
    return cast_table_to_schema(table, schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/table.py", line 2286, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
query: list<item: int64>
  child 0, item: int64
positives: list<item: list<item: int64>>
  child 0, item: list<item: int64>
      child 0, item: int64
negatives: list<item: list<item: int64>>
  child 0, item: list<item: int64>
      child 0, item: int64
to
{'query': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'positives': Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None), 'negatives': Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None), 'neg_score': Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None)}
because column names don't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/cme/tevatron/src/tevatron/driver/train.py", line 120, in <module>
    main()
  File "/home/cme/tevatron/src/tevatron/driver/train.py", line 88, in main
    train_dataset = HFTrainDataset(tokenizer=tokenizer, data_args=data_args,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cme/tevatron/src/tevatron/datasets/dataset.py", line 24, in __init__
    self.dataset = load_dataset(data_args.dataset_name,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/load.py", line 2153, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/chaeyeonjin/miniconda3/lib/python3.11/site-packages/datasets/builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

```

2023-12-03 12:29 UTC, yc-song commented
positive document가 rank 상에 없는 것이 다소 이상하게 느껴집니다. encode -> search -> hard negative mining을 하는 과정에서 굳이 positive doc을 배제하는 코드가 안보입니다.
우리가 이에 대해 연산을 제대로 하고 있는지 확인을 하는 방법은 encoder.py에서 직접 negative documents에 대해 dot product를 해보고, 이것이 실제로 train.rank.tsv에 있는 점수들과 일치하는지 확인하는 것입니다. 한 번 이거를 체크하고 가야할 것 같습니다.

2023-12-03 12:53 UTC, yc-song commented
사실 코드 에러 뜰 때는 내장 함수까지 보실 필요는 없고 말씀대로 우리 코드에서 어떤 에러가 떴는지가 중요합니다.

> {'query': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), 'positives': Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None), 'negatives': Sequence(feature=Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None), length=-1, id=None), 'neg_score': Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None)}
> because column names don't match

이 부분이 중요해 보이고, 우리가 불러오고 있는 train-hn-withscore 디렉토리에 json 파일이 여러 개 있는데, 일부는 query, positives, negatives만 있는 json file이 있고, 여기에 더해 score가 추가된 json file이 있는데, 아마도 이 파일에서 column name이 맞지 않아 문제가 생기는 것으로 보입니다. 내일 미팅 때 같이 확인해봐요.

2023-12-03 12:55 UTC, yc-song requested changes
1. positive doc에 대한 score가 찾아지지 않는 문제
2. json file 여러개가 있는데 각각의 용도가 어떤 차이인지 궁금

2023-12-03 14:43 UTC, hzlcodus commented
train-hn-withscore 폴더는 아래 커맨드로 생긴 건데 실제로 build_train_hn.py에서 만들어지는 파일은 hn이 붙은 json일 거고, json 없는 파일들은 그냥 저 ln -s 커맨드 때문에 train에 있는 파일들이 바로가기처럼 같이 링크된 거라고 보시면 될 것 같습니다..! 저 ln 부분의 정확한 용도는 잘 모르겠는데 그냥 빼버릴까요?

```
SCRIPT_DIR=$PWD
cd marco
python $SCRIPT_DIR/build_train_hn.py --tokenizer_name bert-base-uncased --hn_file ../train.rank.tsv --qrels qrels.train.tsv --queries train.query.txt --collection corpus.tsv --save_to /data/cme/marco/bert/train-hn-withscore-debug
ln -s /data/cme/marco/bert/train/* /data/cme/marco/bert/train-hn-withscore
cd -
```

2023-12-03 16:22 UTC, yc-song commented
네 빼고 실행했을 때 같은 에러가 나는지 한번 보죠

2023-12-04 06:51 UTC, hzlcodus commented
빼고 실행했을 때 이 문제는 해결됐습니다!! 😄 원래 코드는 그럼 원래 train data + HN 이렇게 학습하는 거였던 것 같아요

근데 encoder.py에 들어갔을 때 forward 함수의 파라미터인 pos_passage랑 neg_score가 None으로 들어가는 문제가 있었어서
trainer.py에 들어가서 compute_loss랑 training_step을 바꿔서 해결해보려고 했는데 inputs 가 아예 안 들어오고 있는 것 같습니다.. (커밋을 안 해서 서버 들어가면 파란색으로 보이는 부분들이 수정한 부분입니다!)

data.py의 getitem 리턴 값은(L111) 잘 나오는데도 불구하고 왜 그러는지 모르겠습니다 ㅜㅜ

2024-01-10 11:42 UTC, closed without merging